### ISSUE TITLE
Will this playbook be updated to use CentOS 7?

### ISSUE THREAD

**Issue by stephankaag** [aaron868/management#2]
http://seven.centos.org/2014/07/release-announcement-for-centos-7x86_64/

**Comment by aaron868** [comment]
I will likely update it for CentOS 7 some time in the future but not right away. There are several reasons for this. First, a DISA STIG  must be released for RHEL 7. I base my security settings on it. Ansible must provide modules for the new components like systemd and journald. And I want to see how the new components perform in a production environment over time. There are very new and I want to wait and see how they perform.

Many of the roles should still work in CentOS 7. I am not sure about the logging related roles though.

**Comment by stephankaag** [comment]
Perfectly clear. Thanks for your response!
